### PR TITLE
Cleanup pip install and fix readme example 

### LINKED ISSUE #23: README example not working
**Describe the bug**

```python-traceback
Traceback (most recent call last):
  File "/Users/cthoyt/dev/marius/test.py", line 20, in <module>
    fb15k_example()
  File "/Users/cthoyt/dev/marius/test.py", line 8, in fb15k_example
    train_set, eval_set = m.initializeDatasets(config)
RuntimeError: filesystem error: in copy_file: No such file or directory [training_data/marius/edges/train/edges.bin] [output_dir/train_edges.pt]
```

**To Reproduce**

I took the example from the README verbatim besides fixing the config path

```python
import marius as m

def fb15k_example():
    config_path = "/Users/cthoyt/dev/marius/examples/training/configs/kinships_cpu.ini"
    config = m.parseConfig(config_path)

    train_set, eval_set = m.initializeDatasets(config)

    model = m.initializeModel(config.model.encoder_model, config.model.decoder_model)

    trainer = m.SynchronousTrainer(train_set, model)
    evaluator = m.SynchronousEvaluator(eval_set, model)

    trainer.train(1)
    evaluator.evaluate(True)


if __name__ == "__main__":
    fb15k_example()

```

**Expected behavior**

**Environment**
Mac os 11.2.3 big sur, python 3.9.2, pip installed from latest code on marius

### PR DESCRIPTION
**Pull request by JasonMoho**
- Adds a step in GitHub actions workflow to test the pip install
- Adds fb15k end to end test based on the readme python example
- Updated readme python example to include preprocessing step
- Fix torch GIL issue when calling Trainer.train(). GIL needs to be released for any code which uses the autograd library
- Rename marius directory to marius_package, to avoid issues with python scripts in the root directory that import marius
- Test data cleanup
- Cleanup unnecessary .gitignore entries

Fixes #23

### CODE REVIEW

File: python_bindings/trainer_wrap.cpp [hunk 1]
```diff
@@ -15,7 +15,7 @@ void init_trainer(py::module &m) {
     py::class_<Trainer, PyTrainer>(m, "Trainer")
         .def(py::init<>())
         .def_readwrite("data_set", &Trainer::data_set_)
-        .def("train", &Trainer::train, py::arg("num_epochs") = 1);
+        .def("train", &Trainer::train, py::arg("num_epochs") = 1, py::call_guard<py::gil_scoped_release>());
```
Comment (shivaram) [inline python_bindings/trainer_wrap.cpp:18]: was there a reason to add this? seems like a critical change thats part of a misc edits PR?

Comment (JasonMoho) [reply python_bindings/trainer_wrap.cpp:18]: If this isn't added then the README example will not work and Pytorch throws an error when trainer.train() is called. 

Error:
```
RuntimeError: The autograd engine was called while holding the GIL. 
If you are using the C++ API, the autograd engine is an expensive operation that does not require the GIL to be held so you should release it with 'pybind11::gil_scoped_release no_gil;'. 
If you are not using the C++ API, please report a bug to the pytorch team.
```
Anders and I are aware of these issues and a future PR which adds the custom models will add py::call_guard<py::gil_scoped_release>() to the necessary calls. Similar to how the bindings are structured in this repo: https://github.com/NVIDIA/MinkowskiEngine/blob/master/pybind/extern.hpp#L523
